apiVersion: v1
kind: Service
metadata:
  name: content-web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: content-web-v2
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: content-web
            port:
              number: 80
        path: /
        pathType: Prefix
    host: akshack.eastus.cloudapp.azure.com  # Leave this line commented out until Part 2b