apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  selector:
    matchLabels:
      app: busybox
  replicas: 20
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: k8s.gcr.io/busybox
        command: ["/bin/sh", "-c", "while true; do wget -q -O- hpa-example; done"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80


